name: Continous Integration

on: 
  push: 
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.9.11"
          enable-cache: true

      - name: Installing dependencies
        run: uv sync

      - name: Running linters
        run: uv run task lint

      - name: Mypy checking
        run: uv run task mypy

  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        os: [ubuntu, windows, macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.9.11"
          enable-cache: true

      - name: Installing dependencies
        run: uv sync

      - name: Running tests with pytest
        run: uv run task test
